### ISSUE TITLE
Boolean value shold not Strings

### ISSUE THREAD

**Issue by iwatobipen** [keisuke-yanagisawa/exprorer_msmd#26]
Dear developper,
I got error when I used scheduler_wrapper.py and found a typo.

current line 40 in scheduler_wrapper.py is below
    if environment["use_scheduler"] == "True":

But it should be 
    if environment["use_scheduler"] == True:

Thanks

**Comment by keisuke-yanagisawa** [comment]
Thank you for pointing out. Now 
I fixed and pushed into main branch (with v1.1.3.1 tag).

**Comment by iwatobipen** [comment]
Thanks your prompt reply!!!!!!!
